# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='experience',
            field=models.IntegerField(choices=[(1, 'NONE'), (2, 'SOME'), (3, 'NORMAL'), (4, 'GOOD'), (5, 'PRO')], default=3),
        ),
        migrations.AlterField(
            model_name='survey',
            name='satisfaction_level',
            field=models.IntegerField(choices=[(1, 'BAD'), (2, 'WRONG'), (3, 'NORMAL'), (4, 'GOOD'), (5, 'FANTASTIC')], default=3),
        ),
    ]
